source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_media.gemspec
gemspec

path "../" do
  gem "ubiquo_core"
end

gem "routing-filter"
gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'
