source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_core.gemspec
gemspec

# Using the git version to get 1.9.3 support
path "../" do
  gem "ubiquo_core"
  gem "ubiquo_i18n"
end
gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'

